### ISSUE TITLE
Deprecation means?

### ISSUE THREAD

**Issue by samof76** [cloudfoundry-attic/login-server#53]
Hi.

"The Cloud Foundry Login Server project has been retired. The functionality of the Login Server have been merged into the Cloud Foundry UAA"

Does that mean I do need to include the "login" as part of the cf-deployment manifest???

```
  login:
    analytics:
      code: null
      domain: null
    asset_base_url: null
    brand: oss
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    enabled: true
    invitations_enabled: null
    links:
      home: https://console.esp-perf-rh.internal.ericsson.com
      network: null
      passwd: https://console.esp-perf-rh.internal.ericsson.com/password_resets/new
      signup: https://console.esp-perf-rh.internal.ericsson.com/register
      signup-network: null
    logout:
      redirect:
        url: /login?template=openstack
    messages: null
    notifications:
    ...
```
